VAGRANTFILE_API_VERSION = "2"

IMAGE_NAME = "centos7-aipo-docker"
AIPO_PLAYBOOK = "./playbook_aipo_docker.yml"
IP_ADDRESS = "192.168.1.120"
IMAGE_BOX = "centos/7"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = IMAGE_BOX
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.provider :virtualbox do |vb|
    vb.name = IMAGE_NAME
    vb.memory = "2048"
  end
  config.vm.network "public_network", ip: IP_ADDRESS, bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "../vagrant_share", "/vagrant_data"
  config.vm.synced_folder ".", "/docker_data"
  config.ssh.insert_key = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = AIPO_PLAYBOOK
    ansible.inventory_path = "../hosts"
    ansible.limit = "all"
    ansible.verbose = "v"
  end
  config.vm.provision "docker" do |docker|
    docker.build_image "/docker_data/tomcat",
        args: "-t aipo/tomcat"
    docker.run "aipo/tomcat",
        args: "-p 8080:8080"
  end
  config.vm.provision "docker" do |docker|
    docker.build_image "/docker_data/postres",
        args: "-t aipo/postres"
    docker.run "aipo/postres",
        args: "-p 5432:5432"
  end
end
