app-web:  
  build: ./tomcat
  ports:
    - "8080:8080"
  links:
    - app-db

app-db:  
  build: ./postgres
  expose:
    - "5432"
  volumes_from:
    - app-db-data

app-db-data:  
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data
