VAGRANTFILE_API_VERSION = "2"

IMAGE_NAME = "centos7-aipo-docker"
AIPO_INSTALL_SCRIPT = "./install_aipo.sh"
IP_ADDRESS = "192.168.1.120"
IMAGE_BOX = "centos/7"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = IMAGE_BOX
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.provider :virtualbox do |vb|
    vb.name = IMAGE_NAME
    vb.memory = "2048"
  end
  config.vm.network "public_network", ip: IP_ADDRESS, bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "../vagrant_share", "/vagrant_data"
  config.vm.synced_folder ".", "/docker_data"
  config.ssh.insert_key = false
  config.vm.provision "shell", :path => AIPO_INSTALL_SCRIPT
end
