VAGRANTFILE_API_VERSION = "2"

IMAGE_NAME = "centos6-aipo6.0.2"
AIPO_INSTALL_SCRIPT = "./install_aipo6020.sh"
IP_ADDRESS = "192.168.1.112"
IMAGE_BOX = "centos/6"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = IMAGE_BOX
  config.vm.provider :virtualbox do |vb|
    vb.name = IMAGE_NAME
  end
  config.vm.network "public_network", ip: IP_ADDRESS, bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "../vagrant_share", "/vagrant_data"
  config.vm.provision "shell", :path => AIPO_INSTALL_SCRIPT
  config.ssh.insert_key = false
end
