VAGRANTFILE_API_VERSION = "2"

IMAGE_NAME = "centos7-aipo-latest-ansible"
AIPO_PLAYBOOK = "../playbook_aipo-latest.yml"
IP_ADDRESS = "192.168.1.106"
IMAGE_BOX = "centos/7"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = IMAGE_BOX
  config.vm.provider :virtualbox do |vb|
    vb.name = IMAGE_NAME
    vb.memory = "1024"
  end
  config.vm.network "public_network", ip: IP_ADDRESS, bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "../vagrant_share", "/vagrant_data"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = AIPO_PLAYBOOK
    ansible.inventory_path = "../hosts"
    ansible.limit = "all"
    ansible.verbose = "v"
  end
end
